// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhitelistBot.Data;

#nullable disable

namespace WhitelistBot.Migrations
{
    [DbContext(typeof(WhitelistDataContext))]
    partial class WhitelistDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("WhitelistBot.Data.WhitelistDataContext+WhitelistEntry", b =>
                {
                    b.Property<ulong>("DiscordUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinecraftUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DiscordUserId");

                    b.ToTable("WhitelistEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
